name: Atualizar dados diariamente 

on:
  schedule:
    - cron: "0 7 * * *"    # roda todo dia às 07:00 UTC
  workflow_dispatch:        # permite rodar manual se quiser

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependências
        run: pip install requests
      - name: Rodar script coletor
        run: python coletar_historico.py
      - name: Salvar alterações e enviar ao GitHub
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Atualização automática"
          git push
